### PR TITLE
svg with viewBox attribute results in clipped image.

### PR DESCRIPTION
**Pull request by cjb06776**
Fix clipped images when svg specifies a viewbox attribute, as reported in https://github.com/exupero/saveSvgAsPng/issues/43

Also includes fix for incorrect handling of width attribute when the value is percent that was suggested in https://github.com/exupero/saveSvgAsPng/issues/42

### CODE REVIEW

**Comment by exupero** [comment]
1. Would you create an HTML file with a simple example that reproduces this problem so we can verify future changes don't break it? `index.html` has several different scenarios, if that helps. Don't worry about integrating with `index.html`; that can be done later.
2. It looks like you've only addressed width and not height.
3. Currently, the fallback values of width (`box.width`, `clone.style.width`, etc.) are parsed to integers, but these changes parse only the clone's explicit width. I don't see any reason parsing to an int should be necessary. Can you confirm?

**Comment by exupero** [comment]
Also, check the current `index.html` in a browser to make sure these changes don't cause any regressions compared to http://exupero.org/saveSvgAsPng/

**Comment by cjb06776** [comment]
1. I created a sample - viewboxtest.html.  It is mostly self contained, but I wasn't able to completely reduce it to a trivial example (it uses d3 and an angular directive to create the svg, which is similar to how my app does things and how I was able to reproduce it).  Example below of the problem occurring without and with the fix:
   image
2. Yeah, you are right.  I took your suggested snippet as is, and didn't look at it closer - expanded it to include height as well.
3. The styles do appear to need parseInt still in my tests.  box.[width | height] doesn't from my observations, but the getComputedStyle method I see does return things in the form of "123px" for example.  I've corrected this.
4. I checked index.html, and it looks like it is working as expected.

**Comment by exupero** [comment]
Looks good. One last question: did you find that `box.width` and `box.height` are already integers?

**Comment by cjb06776** [comment]
> Looks good. One last question: did you find that box.width and box.height are already integers?

Yes.

**Pull request merged**
