### PR TITLE
fix XML entities - eg : NBSP

### PR DESCRIPTION
**Pull request by patogalla**
I used in my project, and i have some entities with space characters (& nbsp; ).

The error was : "Entity 'nbsp' not defined"

So, i add all the entities of HTML.

### CODE REVIEW

**Comment by exupero** [comment]
I'd like to add a test for this. Can you give me an example that demonstrates this problem?

**Comment by pgallardodespegar** [comment]
Ok, here you have 2 files : 
- .html for the svg
- and .data for the data image base64 generated (xml encoded).

You have to look at the "& nbsp;" symbol. :smile: 

[example.zip](https://github.com/exupero/saveSvgAsPng/files/368971/example.zip)

**Comment by patogalla** [comment]
Ok, here you have 2 files :

.html for the svg
and .data for the data image base64 generated (xml encoded).
You have to look at the "& nbsp;" symbol. :smile:

[example.zip](https://github.com/exupero/saveSvgAsPng/files/368977/example.zip)

**Comment by exupero** [comment]
I've spot-checked a few entities. `&nbsp;` seems to be the only one that needs to be defined. The others work without being included.

Do you know if this is a browser-specific behavior? In what circumstances do all the entities need to be defined?

**Comment by patogalla** [comment]
Yeah... i didnt try it with all the entities... maybe i should change it, to just `&nbsp;`. 
It was in last Chrome browser.
I made another commit, putting only nbsp.

**Pull request closed without merging**
