### PR TITLE
Support requirejs

### PR DESCRIPTION
**Pull request by thaggie**
To test this functionality tape and requirejs were added as dev dependencies, and so the unit tests can now be ran via `npm test`

### CODE REVIEW

**Comment by exupero** [comment]
Neat! I'll check it out.

It would also be good to update the readme to mention support for requirejs (it already mentions browserify support).

**Comment by ejb** [comment]
Hi, would it be possible to merge this in? Thanks!

**Comment by exupero** [comment]
Thanks. Lost track of this.

**Comment by ejb** [comment]
Great! Thanks for the quick response.

**Pull request merged**
