### PR TITLE
Fix download for iOS devices. (#163)

### PR DESCRIPTION
**Pull request by pawelangelow**
Implement popup for "workaround" download in order to support iOS devices.
Code split download method and introduce helpers.

### CODE REVIEW

**Comment by exupero** [comment]
Thanks for the fix. I added ba5c562d23cc740d10c00cd26c809befcf88251c which should do the same thing but with less indirection. Let me know if it doesn't work for you.

**Comment by pawelangelow** [comment]
@exupero, the actual problem is that you can't create popup [ba5c562](https://github.com/exupero/saveSvgAsPng/commit/ba5c562d23cc740d10c00cd26c809befcf88251c) there, because, as it is mentioned [here](https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari/39387533#39387533), **safari is blocking any call to window.open() which is made inside an async call**. With few words: it is too late. 

One possible solution is:

- when user has triggered the event, open popup from the event handler
- in the same event handler trigger the image processing functions as it is now
- when result is ready, you can populate the opened popup in the first step with desired content (you have to keep reference to the popup)

Pseudocode:
```
<button onClick=() => {
    const popup = window.open();
    processing.then((result) => {
        popup.updateContent(result);
    }
)}>
```

In the current codebase, popup initialisation has to be [here](https://github.com/exupero/saveSvgAsPng/commit/ba5c562d23cc740d10c00cd26c809befcf88251c#diff-0f560c736d20d61f38eb347eaa30eb10L383), before return, and somehow pass the reference to the popup for using it [here](https://github.com/exupero/saveSvgAsPng/commit/ba5c562d23cc740d10c00cd26c809befcf88251c#diff-0f560c736d20d61f38eb347eaa30eb10L371) .

```
out$.download = (name, uri) => {
   ......
       // THIS WONT WORK, CHECK SCREENSHOT
        const popup = window.open();
       // Instead, use the reference created in the out$.saveSvg
        popup.document.title = name;
        popup.location.replace(uri);
      }
    }
  };
  out$.saveSvg = (el, name, options) => {
    const popup = window.open();
    return ....
  };
```

Screenshot 2019-05-09 at 11 35 09

If you create the popup in the event handler, everything works as expected.
Screenshot 2019-05-09 at 11 49 01

**Comment by exupero** [comment]
Thanks for the clarifications. Please check whether f0df944 works for you.

**Comment by pawelangelow** [comment]
Yup, it is working now. Thanks 😃

**Comment by exupero** [comment]
Published version 1.4.14 to NPM with these changes.

**Pull request closed without merging**
